exclude: '^.*\.(md|MD|xml|ini|cfg|txt)$|^\.idea/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        # Check if YAML files are correctly formatted
      - id: check-json
        # Check if JSON files are correctly formatted
      - id: trailing-whitespace
        # Remove trailing whitespace
      - id: check-added-large-files
        # Check if large files are mistakenly added to git
      - id: end-of-file-fixer
        # Ensure files end with a single newline
      - id: mixed-line-ending
        # Standardize the line endings in files (e.g., convert CRLF to LF)
        args: [ "--fix=lf" ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: \.(py|sh|rst|yml|yaml)$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        # Sort and format Python import statements
        args:
          [
            "--profile",
            "black",
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--line-width=88",
          ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        # Remove unused imports and variables
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        # Upgrade Python code to newer versions of Python syntax
        args: [ "--py310-plus" ]

  - repo: https://github.com/psf/black
    rev: "24.8.0"
    hooks:
      - id: black
        # Automatically format Python code to conform to PEP 8 style guide
        args: [--line-length=88]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        # Ensure commit messages follow the Conventional Commits standard
        stages: [ commit-msg ]

  - repo: 'https://github.com/PyCQA/flake8'
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - '--max-line-length=88'
          - '--ignore=E203,W503,F401'
        language: python
        types: [ python ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports,--disallow-untyped-defs, --show-error-codes ]
#          additional_dependencies: [ types-requests, types-setuptools ]  # If additional type stubs are needed

ci:
    # Settings for the https://pre-commit.ci/ continuous integration service
    autofix_prs: True
    # Default message is more verbose
    autoupdate_commit_msg: '[pre-commit.ci] autoupdate'
    # Default is weekly
    autoupdate_schedule: monthly
